# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Christian Brabez
tagline:          'The personal website of Christian Brabez'
description:      'The personal website of Christian Brabez'
url:              joshualande.com

author:
  name:           'Christian Brabez'
  url:            https://twitter.com/cbrabez

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/cbrabez/cbrabez.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
